version: '3'
networks:
  internal:
    driver: bridge 

services:
  traefik:
    image: traefik:v2.6.0
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/arkime/traefik:/etc/traefik:ro
    networks:
      - internal

  elasticsearch:
    image: elasticsearch:7.17.0
    hostname: elasticsearch
    labels:
      - traefik.enable=true
      - traefik.http.routers.elastic.entrypoints=web
      - traefik.http.routers.elastic.rule=Host(`elastic.rskdev.io`)
      - traefik.http.routers.elastic.service=elastic@docker
      - traefik.http.services.elastic.loadbalancer.server.port=9200
#      - traefik.http.services.elastic.loadbalancer.sticky=true
#      - traefik.http.services.elastic.loadbalancer.sticky.cookie.name=elastic-session-token
    environment:
      - discovery.type=single-node
    depends_on:
      - traefik
    networks: 
      - internal

  viewer:
    image: arkime:3.3.1-1
    hostname: viewer
    labels: 
      - traefik.enable=true
      - traefik.http.routers.arkime.entrypoints=web
      - traefik.http.routers.arkime.rule=Host(`arkime.rskdev.io`)
      - traefik.http.routers.arkime.service=arkime@docker
      - traefik.http.services.arkime.loadbalancer.server.port=8005
#      - traefik.http.services.arkime.loadbalancer.sticky=true
#      - traefik.http.services.arkime.loadbalancer.sticky.cookie.name=arkime-session-token
    environment:
      - ES_HOST=elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - ./log:/opt/arkime/local/log
    networks:
      - internal
    entrypoint: /opt/arkime/local/bin/viewer.sh

  import:
    image: arkime:3.3.1-1
    hostname: import
    environment:
      - ES_HOST=elasticsearch
      - ARKIME_VIEWER=viewer
    depends_on:
      - viewer
    volumes:
      - ./import:/import:rw
    networks:
      - internal
    entrypoint: /opt/arkime/local/bin/import.sh
