version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: elasticsearch
    environment:
      - discovery.type=single-node

  viewer:
    build:
      context: .
    image: rskntroot/arkime:2.7.1-1
    hostname: viewer
    environment:
      - ARKIME_USER=root
      - ARKIME_PSWD=arkime-pswd
    depends_on:
      - elasticsearch
    volumes:
      - ./arkime/log:/opt/arkime/log
    entrypoint: /opt/arkime/bin/viewer.sh 

  import:
    image: rskntroot/arkime:2.7.1-1
    hostname: import
    depends_on:
      - elasticsearch
    volumes:
      - ./arkime/import:/import
    entrypoint: /opt/arkime/bin/import.sh

  nginx:
    image: nginx:mainline-alpine
    hostname: nginx
    volumes:
      - ./nginx/etc/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx:rw
      - ./nginx/ssl:/ssl:ro
    depends_on:
      - viewer
    ports:
      - 80:80
