version: '3'
networks:
  internal:
    driver: bridge 
  external:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    networks: 
      - internal

  viewer:
    image: rskntroot/arkime:3.0.0-1
    hostname: viewer
    environment:
      - ARKIME_USER=root
      - ARKIME_PSWD=arkime-pswd
    depends_on:
      - elasticsearch
    volumes:
      - ./log:/arkime/log
    networks:
      - internal
    entrypoint: /arkime/bin/viewer.sh

  import:
    image: rskntroot/arkime:3.0.0-1
    hostname: import
    depends_on:
      - elasticsearch
      - viewer
    environment:
      - ARKIME_USER=root
      - ARKIME_PSWD=arkime-pswd
    volumes:
      - ./log:/arkime/log
      - ./import:/import
    networks:
      - internal
    entrypoint: /arkime/bin/import.sh

  nginx:
    image: nginx:mainline-alpine
    hostname: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/ssl:ro
      - ./log:/var/log/nginx:rw
    depends_on:
      - viewer
    networks: 
      - internal
      - external
    ports:
      - 80:80
