version: '3'
networks:
  internal:
    driver: bridge 

services:
  traefik:
    image: traefik:v2.6.0
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/arkime/traefik:/etc/traefik:ro
    networks:
      - internal

  elasticsearch:
    image: elasticsearch:7.17.0
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    depends_on:
      - traefik
    networks: 
      - internal

  viewer:
    image: arkime:3.3.1-1
    hostname: viewer
    environment:
      - ARKIME_USER=root
      - ARKIME_PSWD=arkime-pswd
      - ES_HOST=elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - ./log:/opt/arkime/local/log
    networks:
      - internal
    entrypoint: /opt/arkime/local/bin/viewer.sh

  import:
    image: arkime:3.3.1-1
    hostname: import
    environment:
      - ARKIME_USER=root
      - ARKIME_PSWD=arkime-pswd
      - ES_HOST=elasticsearch
      - ARKIME_VIEWER=viewer
    depends_on:
      - viewer
    volumes:
      - ./import:/import:rw
    networks:
      - internal
    entrypoint: /opt/arkime/local/bin/import.sh
