global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  web:
    address: :80
    http:
#      redirections:
#        entryPoint:
#          to: websecure
#          priority: 10
#  websecure:
#    address: :443
log:
  level: INFO
accessLog:
  format: common
api:
  insecure: true
providers:
  docker:
    endpoint: unix:///var/run/docker.sock 
    network: arkime_internal
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
